//! Quality snapshot for wave, generated by sdsp-test-kit.
//!
//! For an instrument the first question is not "how does it sound" but "does
//! every note make a sound at all" — SuperDuper Drum shipped for months with
//! hats and clap mapped to notes nothing sent, and nothing caught it.
//!
//!     SDSP_UPDATE_SNAPSHOTS=1 cargo test -p superduper-wave --test quality

use sdsp_test_kit::probes::{self, db};
use sdsp_test_kit::{render_instrument, PluginUnderTest, Suite};

struct Target;
impl PluginUnderTest for Target {
    type Plugin = superduper_wave::SuperDuperWave;
    const ID: &'static std::ffi::CStr = c"co.superduperai.wave";
}

const SR: f64 = 48_000.0;

#[test]
fn every_note_sounds() {
    // A spread across the range the instrument is played in. Drum maps voices
    // to specific pitches, so this doubles as a note-map regression test.
    for key in [36, 38, 40, 42, 46, 48, 55, 60, 67, 72] {
        let (l, r) = render_instrument::<Target>(SR, key, 0.5, 1.0);
        let level = db(probes::rms(&l).max(probes::rms(&r)));
        assert!(
            level > -70.0,
            "note {key} produced {level:.1} dB — effectively silence. \
             If this note is deliberately unmapped, exclude it here explicitly."
        );
    }
}

#[test]
fn quality_snapshot() {
    let mut s = Suite::new("wave", concat!(env!("CARGO_MANIFEST_DIR"), "/tests/quality.snap"))
        .default_tolerance(1.5);

    for key in [36, 48, 60, 72] {
        let (l, _) = render_instrument::<Target>(SR, key, 0.5, 1.5);
        s.record(format!("note{key}_rms_db"), db(probes::rms(&l)));
        s.record(format!("note{key}_peak_db"), db(probes::peak(&l)));
        s.record(format!("note{key}_max_step"), probes::max_step(&l));
        for (band, level) in probes::band_shape(&l, SR as f32) {
            s.record(format!("note{key}_band_{band}"), level);
        }
    }
    s.finish();
}
