//! Quality snapshot for harmonic, generated by sdsp-test-kit.
//!
//! Fixed probes through the real CLAP plugin, recorded to `tests/quality.snap`.
//! A change in any of these numbers is a change in how the plugin sounds, and
//! the test fails until the snapshot is re-recorded on purpose:
//!
//!     SDSP_UPDATE_SNAPSHOTS=1 cargo test -p superduper-harmonic --test quality

use sdsp_test_kit::probes::{self, db};
use sdsp_test_kit::{render_effect, PluginUnderTest, Suite};

struct Target;
impl PluginUnderTest for Target {
    type Plugin = superduper_harmonic::SuperDuperHarmonic;
    const ID: &'static std::ffi::CStr = c"co.superduperai.harmonic";
}

const SR: f64 = 48_000.0;

#[test]
fn quality_snapshot() {
    // Wider than the default: several plugins have noise sources or LFOs that
    // do not restart identically, and a snapshot that flaps teaches people to
    // ignore it.
    let mut s = Suite::new("harmonic", concat!(env!("CARGO_MANIFEST_DIR"), "/tests/quality.snap"))
        .default_tolerance(1.0);
    let frames = 1 << 15;

    let tone = probes::tone(SR as f32, 1000.0, 0.5, frames);
    let (out, _) = render_effect::<Target>(SR, &tone, &tone);
    s.record("tone_gain_db", probes::gain_db(&tone, &out));
    s.record("tone_peak_db", db(probes::peak(&out)));
    s.record("tone_thd_db", probes::thd_at(&out, 1000.0, SR as f32));
    for (band, level) in probes::band_shape(&out, SR as f32) {
        s.record(format!("tone_band_{band}"), level);
    }

    let noise = probes::noise(frames, 0.3);
    let (nout, _) = render_effect::<Target>(SR, &noise, &noise);
    s.record("noise_gain_db", probes::gain_db(&noise, &nout));
    s.record("noise_max_step", probes::max_step(&nout));
    for (band, level) in probes::band_shape(&nout, SR as f32) {
        s.record(format!("noise_band_{band}"), level);
    }

    // An impulse shows the tail: reverbs, delays and filters all differ here,
    // and a dead tail is the classic "plugin silently stopped working".
    let imp = probes::impulse(frames);
    let (iout, _) = render_effect::<Target>(SR, &imp, &imp);
    s.record("impulse_rms_db", db(probes::rms(&iout)));
    s.record("impulse_peak_db", db(probes::peak(&iout)));

    s.finish();
}
