[package]
name = "superduper-dsp-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SDK for writing SuperDuper DSP effects"

[lib]
crate-type = ["rlib"]

[dependencies]
superduper-dsp-sdk-macros = { path = "../sdk-macros" }
clack-plugin = "0.1"
clack-common = "0.1"
clack-extensions = { version = "0.1", features = ["params", "audio-ports", "state", "clack-plugin"] }
atomic_float = "1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
