//! Quality snapshot for sampler, generated by sdsp-test-kit.
//!
//! For an instrument the first question is not "how does it sound" but "does
//! every note make a sound at all" — SuperDuper Drum shipped for months with
//! hats and clap mapped to notes nothing sent, and nothing caught it.
//!
//!     SDSP_UPDATE_SNAPSHOTS=1 cargo test -p superduper-sampler --test quality

use sdsp_test_kit::probes::{self, db};
use sdsp_test_kit::{render_instrument, PluginUnderTest, Suite};

struct Target;
impl PluginUnderTest for Target {
    type Plugin = superduper_sampler::SuperDuperSampler;
    const ID: &'static std::ffi::CStr = c"co.superduperai.sampler";
}

const SR: f64 = 48_000.0;

// No `every_note_sounds` here, on purpose: the Sampler plays WAV files, and a
// fresh instance has none loaded, so silence on every key is correct behaviour
// rather than a fault. Give it a sample and the snapshot below has content;
// without one it records the empty state, which is still worth pinning — a
// change that makes an unloaded sampler emit anything is a bug.

#[test]
fn quality_snapshot() {
    let mut s = Suite::new("sampler", concat!(env!("CARGO_MANIFEST_DIR"), "/tests/quality.snap"))
        .default_tolerance(1.5);

    for key in [36, 48, 60, 72] {
        let (l, _) = render_instrument::<Target>(SR, key, 0.5, 1.5);
        s.record(format!("note{key}_rms_db"), db(probes::rms(&l)));
        s.record(format!("note{key}_peak_db"), db(probes::peak(&l)));
        s.record(format!("note{key}_max_step"), probes::max_step(&l));
        for (band, level) in probes::band_shape(&l, SR as f32) {
            s.record(format!("note{key}_band_{band}"), level);
        }
    }
    s.finish();
}
